# Generated by Django 5.2 on 2025-05-07 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Eventmain",
            "0003_auditlog_booking_event_eventanalytics_eventreview_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizer",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_organizers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
